[Icon Theme]
Name=Nyhil-Barren
Comment=A Black-Metal inspired icon pack, forked from Papirus
Inherits=Papirus-Dark,hicolor
Example=folder

Directories=16x16/apps,16x16/places,16x16/mimetypes,16x16/devices,16x16/actions,16x16/status,22x22/apps,22x22/places,22x22/mimetypes,22x22/devices,22x22/actions,22x22/status,32x32/apps,32x32/places,32x32/mimetypes,32x32/devices,32x32/actions,32x32/status,48x48/apps,48x48/places,48x48/mimetypes,48x48/devices,48x48/actions,48x48/status,96x96/apps,96x96/places,96x96/mimetypes,96x96/devices,96x96/actions,96x96/status,128x128/apps,128x128/places,128x128/mimetypes,128x128/devices,128x128/actions,128x128/status,256x256/apps,256x256/places,256x256/mimetypes,256x256/devices,256x256/actions,256x256/status,512x512/apps,512x512/places,512x512/mimetypes,512x512/devices,512x512/actions,512x512/status

[16x16/apps]
Size=16
Context=Applications
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[16x16/mimetypes]
Size=16
Context=MimeTypes
Type=Fixed

[16x16/devices]
Size=16
Context=Devices
Type=Fixed

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[16x16/status]
Size=16
Context=Status
Type=Fixed

[22x22/apps]
Size=22
Context=Applications
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[22x22/mimetypes]
Size=22
Context=MimeTypes
Type=Fixed

[22x22/devices]
Size=22
Context=Devices
Type=Fixed

[22x22/actions]
Size=22
Context=Actions
Type=Fixed

[22x22/status]
Size=22
Context=Status
Type=Fixed

[32x32/apps]
Size=32
Context=Applications
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[32x32/mimetypes]
Size=32
Context=MimeTypes
Type=Fixed

[32x32/devices]
Size=32
Context=Devices
Type=Fixed

[32x32/actions]
Size=32
Context=Actions
Type=Fixed

[32x32/status]
Size=32
Context=Status
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[48x48/mimetypes]
Size=48
Context=MimeTypes
Type=Fixed

[48x48/devices]
Size=48
Context=Devices
Type=Fixed

[48x48/actions]
Size=48
Context=Actions
Type=Fixed

[48x48/status]
Size=48
Context=Status
Type=Fixed

[96x96/apps]
Size=96
Context=Applications
Type=Fixed

[96x96/places]
Size=96
Context=Places
Type=Fixed

[96x96/mimetypes]
Size=96
Context=MimeTypes
Type=Fixed

[96x96/devices]
Size=96
Context=Devices
Type=Fixed

[96x96/actions]
Size=96
Context=Actions
Type=Fixed

[96x96/status]
Size=96
Context=Status
Type=Fixed

[128x128/apps]
Size=128
Context=Applications
Type=Fixed

[128x128/places]
Size=128
Context=Places
Type=Fixed

[128x128/mimetypes]
Size=128
Context=MimeTypes
Type=Fixed

[128x128/devices]
Size=128
Context=Devices
Type=Fixed

[128x128/actions]
Size=128
Context=Actions
Type=Fixed

[128x128/status]
Size=128
Context=Status
Type=Fixed

[256x256/apps]
Size=256
Context=Applications
Type=Fixed

[256x256/places]
Size=256
Context=Places
Type=Fixed

[256x256/mimetypes]
Size=256
Context=MimeTypes
Type=Fixed

[256x256/devices]
Size=256
Context=Devices
Type=Fixed

[256x256/actions]
Size=256
Context=Actions
Type=Fixed

[256x256/status]
Size=256
Context=Status
Type=Fixed

[512x512/apps]
Size=512
Context=Applications
Type=Fixed

[512x512/places]
Size=512
Context=Places
Type=Fixed

[512x512/mimetypes]
Size=512
Context=MimeTypes
Type=Fixed

[512x512/devices]
Size=512
Context=Devices
Type=Fixed

[512x512/actions]
Size=512
Context=Actions
Type=Fixed

[512x512/status]
Size=512
Context=Status
Type=Fixed
